'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';

import { apiClient } from '@/lib/api';

type Envelope<T>={success:true;data:T};
type Reward={claimed_today:boolean;claim:{streak_day:number;coins:number}|null;next_streak_day:number;next_coins:number;calendar:number[]};
type Referral={code:string;share_url:string;invited:number;earned_coins:number;applied:boolean};

export default function RewardsPage(){const client=useQueryClient(),[code,setCode]=useState('');const reward=useQuery({queryKey:['reward'],queryFn:async()=>(await apiClient.get<Envelope<Reward>>('/rewards/daily')).data.data});const referral=useQuery({queryKey:['referral'],queryFn:async()=>(await apiClient.get<Envelope<Referral>>('/referrals/me')).data.data});const claim=useMutation({mutationFn:()=>apiClient.post('/rewards/daily/claim'),onSuccess:()=>client.invalidateQueries({queryKey:['reward']})});const apply=useMutation({mutationFn:()=>apiClient.post('/referrals/apply',{code}),onSuccess:()=>client.invalidateQueries({queryKey:['referral']})});return <main className="mx-auto max-w-4xl px-5 py-12"><p className="text-xs font-black tracking-[.25em] text-[var(--accent)]">GROW WITH DROVIXA</p><h1 className="mt-3 text-4xl font-black">Rewards & referrals</h1><div className="mt-8 grid gap-5 md:grid-cols-2"><section className="rounded-3xl bg-[var(--card)] p-7"><h2 className="text-2xl font-black">Daily streak</h2><p className="mt-2 text-[var(--muted)]">{reward.data?.claimed_today?`Day ${reward.data.claim?.streak_day} claimed · +${reward.data.claim?.coins} coins`:`Next reward: ${reward.data?.next_coins??5} coins`}</p><div className="mt-5 grid grid-cols-7 gap-2">{(reward.data?.calendar??[5,5,10,10,15,20,50]).map((coins,index)=><div className="rounded-xl bg-white/5 p-2 text-center" key={index}><small className="text-[var(--muted)]">D{index+1}</small><strong className="mt-1 block">{coins}</strong></div>)}</div><button disabled={reward.data?.claimed_today||claim.isPending} onClick={()=>claim.mutate()} className="primary-button mt-6 w-full disabled:opacity-40">{reward.data?.claimed_today?'Come back tomorrow':'Claim daily coins'}</button></section><section className="rounded-3xl bg-[var(--card)] p-7"><h2 className="text-2xl font-black">Invite friends</h2><p className="mt-5 text-3xl font-black tracking-widest text-[var(--accent)]">{referral.data?.code??'—'}</p><p className="mt-2 text-[var(--muted)]">{referral.data?.invited??0} friends · {referral.data?.earned_coins??0} coins</p><button onClick={()=>referral.data&&navigator.clipboard.writeText(`${referral.data.code} ${referral.data.share_url}`)} className="secondary-button mt-5 w-full">Copy invite</button>{!referral.data?.applied?<div className="mt-5 flex gap-2"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Referral code" className="min-h-12 flex-1 rounded-2xl bg-white/5 px-4 outline-none"/><button onClick={()=>apply.mutate()} className="primary-button">Apply</button></div>:<p className="mt-5 text-green-300">✓ Referral applied</p>}</section></div></main>}
