'use client';

import { useMutation, useQuery } from '@tanstack/react-query';
import { useParams } from 'next/navigation';
import { useState } from 'react';

import { apiClient } from '@/lib/api';

type Envelope<T>={success:true;data:T};
type Party={invite_code:string;title:string;share_url:string;status:string;paused:boolean;position_seconds:number;is_host:boolean;max_members:number;members:{user_id:string;name:string;role:string}[];messages:{id:string;name:string;message:string}[]};

export default function WatchPartyPage(){const {code}=useParams<{code:string}>(),[text,setText]=useState('');const query=useQuery({queryKey:['party',code],queryFn:async()=>(await apiClient.get<Envelope<Party>>(`/watch-parties/${code}`)).data.data,retry:false,refetchInterval:3000});const join=useMutation({mutationFn:()=>apiClient.post(`/watch-parties/${code}/join`,{}),onSuccess:()=>query.refetch()});const control=useMutation({mutationFn:(paused:boolean)=>apiClient.patch(`/watch-parties/${code}/state`,{position_seconds:query.data?.position_seconds??0,paused,status:paused?'paused':'playing'}),onSuccess:()=>query.refetch()});const send=useMutation({mutationFn:()=>apiClient.post(`/watch-parties/${code}/messages`,{message:text}),onSuccess:()=>{setText('');void query.refetch()}});if(query.isError)return <main className="mx-auto max-w-xl px-5 py-20 text-center"><h1 className="text-4xl font-black">Join Watch Party</h1><p className="mt-3 text-[var(--muted)]">Invite code {code}</p><button onClick={()=>join.mutate()} className="primary-button mt-7">Join party</button></main>;const party=query.data;return <main className="mx-auto max-w-4xl px-5 py-12"><p className="text-xs font-black tracking-[.25em] text-[var(--accent)]">WATCH TOGETHER</p><h1 className="mt-3 text-4xl font-black">{party?.title??'Loading…'}</h1>{party?<div className="mt-8 grid gap-5 md:grid-cols-2"><section className="rounded-3xl bg-[var(--card)] p-7"><p className="text-3xl font-black tracking-widest text-[var(--accent)]">{party.invite_code}</p><p className="mt-2 text-[var(--muted)]">{party.members.length}/{party.max_members} people · {party.status}</p><button onClick={()=>navigator.clipboard.writeText(party.share_url)} className="secondary-button mt-5 w-full">Copy invite</button>{party.is_host?<button onClick={()=>control.mutate(!party.paused)} className="primary-button mt-3 w-full">{party.paused?'▶ Play together':'Ⅱ Pause'}</button>:null}<h2 className="mt-7 text-xl font-black">People</h2>{party.members.map(m=><p key={m.user_id} className="mt-2">{m.role==='host'?'★':'•'} {m.name}</p>)}</section><section className="rounded-3xl bg-[var(--card)] p-7"><h2 className="text-xl font-black">Party chat</h2><div className="mt-4 max-h-72 space-y-3 overflow-auto">{party.messages.map(m=><div key={m.id} className="rounded-2xl bg-white/5 p-3"><strong>{m.name}</strong><p className="mt-1 text-[var(--muted)]">{m.message}</p></div>)}</div><div className="mt-4 flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Say something…" className="min-h-12 flex-1 rounded-2xl bg-white/5 px-4 outline-none"/><button onClick={()=>send.mutate()} className="primary-button">Send</button></div></section></div>:null}</main>}
