import { useQuery } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { ContentCard } from '@/components/ContentCard';
import { EmptyState, ErrorState, LoadingState } from '@/components/ScreenStates';
import { getTrendingSearches, searchContent } from '@/features/catalog/api';
import { colors } from '@/theme';

export default function SearchScreen(){const[input,setInput]=useState(''),[query,setQuery]=useState('');useEffect(()=>{const id=setTimeout(()=>setQuery(input.trim()),300);return()=>clearTimeout(id)},[input]);const results=useQuery({queryKey:['search',query],queryFn:()=>searchContent(query),enabled:query.length>=2});const trending=useQuery({queryKey:['search','trending'],queryFn:getTrendingSearches});return <ScrollView style={s.screen} contentContainerStyle={s.content}><TextInput autoFocus value={input} onChangeText={setInput} placeholder="Series, movies, actors, genres…" placeholderTextColor={colors.muted} style={s.input}/>{!query?<><Text style={s.heading}>Trending searches</Text><View style={s.chips}>{trending.data?.map(x=><Pressable key={x} style={s.chip} onPress={()=>setInput(x)}><Text style={s.chipText}>{x}</Text></Pressable>)}</View></>:null}{results.isPending&&query?<LoadingState label="Searching…"/>:null}{results.isError?<ErrorState retry={()=>void results.refetch()}/>:null}{results.data?results.data.length?<View style={s.grid}>{results.data.map(x=><ContentCard key={x.id} item={x}/>)}</View>:<EmptyState title="No results" body="Try a different title, actor, genre or keyword."/>:null}</ScrollView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:18,paddingBottom:36},input:{height:54,borderRadius:18,paddingHorizontal:17,color:colors.text,backgroundColor:colors.card,fontSize:16},heading:{color:colors.text,fontSize:20,fontWeight:'900',marginTop:26,marginBottom:14},chips:{flexDirection:'row',flexWrap:'wrap',gap:9},chip:{paddingHorizontal:14,paddingVertical:10,borderRadius:99,backgroundColor:colors.card},chipText:{color:colors.muted,fontWeight:'700'},grid:{flexDirection:'row',flexWrap:'wrap',gap:14,marginTop:24}});
