import { useMutation, useQuery } from '@tanstack/react-query';
import axios from 'axios';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, Share, StyleSheet, Text, TextInput, View } from 'react-native';

import { getWatchParty, joinWatchParty, sendWatchPartyMessage, updateWatchParty } from '@/features/growth/api';
import { colors } from '@/theme';

const errorMessage=(e:unknown)=>axios.isAxiosError(e)?e.response?.data?.error?.message??'Request failed.':'Request failed.';
export default function WatchPartyScreen(){const {code=''}=useLocalSearchParams<{code:string}>(),router=useRouter(),[text,setText]=useState('');const party=useQuery({queryKey:['watch-party',code],queryFn:()=>getWatchParty(code),retry:false,refetchInterval:3000});const join=useMutation({mutationFn:()=>joinWatchParty(code),onSuccess:()=>party.refetch(),onError:e=>Alert.alert('Watch Party',errorMessage(e))});const state=useMutation({mutationFn:(paused:boolean)=>updateWatchParty(code,{position_seconds:party.data?.position_seconds??0,paused,status:paused?'paused':'playing'}),onSuccess:()=>party.refetch()});const send=useMutation({mutationFn:()=>sendWatchPartyMessage(code,text),onSuccess:()=>{setText('');void party.refetch();}});if(party.isError)return <View style={s.center}><Text style={s.title}>Join Watch Party</Text><Text style={s.muted}>Code {code}</Text><Pressable style={s.button} onPress={()=>join.mutate()}><Text style={s.buttonText}>{join.isPending?'Joining…':'Join party'}</Text></Pressable></View>;const p=party.data;return <ScrollView style={s.screen} contentContainerStyle={s.content}><Text style={s.eyebrow}>WATCH TOGETHER</Text><Text style={s.title}>{p?.title??'Loading party…'}</Text>{p?<><View style={s.card}><Text style={s.code}>{p.invite_code}</Text><Text style={s.muted}>{p.members.length}/{p.max_members} people · {p.status}</Text><Pressable style={s.outline} onPress={()=>Share.share({message:`Join my Drovixa Watch Party: ${p.share_url}`})}><Text style={s.outlineText}>Share invite</Text></Pressable>{p.is_host?<View style={s.controls}><Pressable style={s.button} onPress={()=>state.mutate(!p.paused)}><Text style={s.buttonText}>{p.paused?'▶ Play together':'Ⅱ Pause'}</Text></Pressable><Pressable style={s.outline} onPress={()=>router.push({pathname:'/watch/[id]',params:{id:p.episode_id??p.content_id,target:p.episode_id?'episode':'movie'}})}><Text style={s.outlineText}>Open player</Text></Pressable></View>:null}</View><View style={s.card}><Text style={s.cardTitle}>People</Text>{p.members.map(m=><Text key={m.user_id} style={s.person}>{m.role==='host'?'★':'•'} {m.name}</Text>)}</View><View style={s.card}><Text style={s.cardTitle}>Party chat</Text>{p.messages.map(m=><View key={m.id} style={s.message}><Text style={s.person}>{m.name}</Text><Text style={s.muted}>{m.message}</Text></View>)}<View style={s.chatRow}><TextInput value={text} onChangeText={setText} placeholder="Say something…" placeholderTextColor={colors.muted} style={s.input}/><Pressable disabled={!text.trim()} onPress={()=>send.mutate()} style={s.small}><Text style={s.buttonText}>Send</Text></Pressable></View></View></>:null}</ScrollView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:20,paddingBottom:50},center:{flex:1,alignItems:'center',justifyContent:'center',padding:30,backgroundColor:colors.background},eyebrow:{color:colors.accent,fontSize:10,fontWeight:'900',letterSpacing:1.5},title:{color:colors.text,fontSize:32,fontWeight:'900',marginTop:7,marginBottom:20,textAlign:'center'},card:{padding:20,borderRadius:24,backgroundColor:colors.card,marginBottom:16},cardTitle:{color:colors.text,fontSize:20,fontWeight:'900',marginBottom:12},code:{color:colors.accent,fontSize:28,fontWeight:'900',letterSpacing:3},muted:{color:colors.muted,marginTop:5,lineHeight:20},button:{alignItems:'center',padding:14,borderRadius:99,backgroundColor:colors.accent,marginTop:16},buttonText:{color:colors.text,fontWeight:'900'},outline:{alignItems:'center',padding:14,borderRadius:99,borderWidth:1,borderColor:colors.line,marginTop:12},outlineText:{color:colors.text,fontWeight:'900'},controls:{marginTop:5},person:{color:colors.text,fontWeight:'800',marginVertical:5},message:{paddingVertical:8,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line},chatRow:{flexDirection:'row',gap:8,marginTop:14},input:{flex:1,minHeight:50,paddingHorizontal:14,borderRadius:15,backgroundColor:colors.cardSecondary,color:colors.text},small:{justifyContent:'center',paddingHorizontal:18,borderRadius:15,backgroundColor:colors.accent}});
