"""phase 2 content catalog

Revision ID: 20260813_0002
Revises: 20260812_0001
Create Date: 2026-08-13 13:45:33.797291
"""
import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

from alembic import op
import sqlalchemy as sa


revision: str = "20260813_0002"
down_revision: str | None = "20260812_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

UUID_NAMESPACE = uuid.UUID("cb1e7fd2-f7c2-45e6-bf36-1473536af29e")


def stable_id(kind: str, value: str) -> uuid.UUID:
    return uuid.uuid5(UUID_NAMESPACE, f"{kind}:{value}")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(code) = 2', name=op.f('ck_countries_code_length')),
    sa.CheckConstraint('length(currency) = 3', name=op.f('ck_countries_currency_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries'))
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=False)
    op.create_table('genres',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres'))
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=False)
    op.create_index(op.f('ix_genres_slug'), 'genres', ['slug'], unique=True)
    op.create_table('languages',
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('native_name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages'))
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('video_assets',
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('provider_asset_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('uploading', 'processing', 'ready', 'failed', 'deleted', name='video_status'), server_default='uploading', nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('playback_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name=op.f('ck_video_assets_duration')),
    sa.CheckConstraint('height IS NULL OR height > 0', name=op.f('ck_video_assets_height')),
    sa.CheckConstraint('width IS NULL OR width > 0', name=op.f('ck_video_assets_width')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_assets')),
    sa.UniqueConstraint('provider', 'provider_asset_id', name='provider_asset')
    )
    op.create_index(op.f('ix_video_assets_playback_id'), 'video_assets', ['playback_id'], unique=False)
    op.create_index(op.f('ix_video_assets_provider'), 'video_assets', ['provider'], unique=False)
    op.create_index(op.f('ix_video_assets_status'), 'video_assets', ['status'], unique=False)
    op.create_table('actors',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('photo_url', sa.String(length=2048), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_actors_country_id_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actors'))
    )
    op.create_index(op.f('ix_actors_country_id'), 'actors', ['country_id'], unique=False)
    op.create_index(op.f('ix_actors_name'), 'actors', ['name'], unique=False)
    op.create_index(op.f('ix_actors_slug'), 'actors', ['slug'], unique=True)
    op.create_table('content',
    sa.Column('type', sa.Enum('series', 'movie', name='content_type'), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('slug', sa.String(length=260), nullable=False),
    sa.Column('original_title', sa.String(length=240), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=2048), nullable=True),
    sa.Column('backdrop_url', sa.String(length=2048), nullable=True),
    sa.Column('trailer_url', sa.String(length=2048), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('original_language_id', sa.Uuid(), nullable=True),
    sa.Column('age_rating', sa.Enum('all', '7+', '13+', '16+', '18+', name='age_rating'), server_default='all', nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'published', 'archived', name='content_status'), server_default='draft', nullable=False),
    sa.Column('visibility', sa.Enum('public', 'unlisted', 'private', 'scheduled', name='content_visibility'), server_default='private', nullable=False),
    sa.Column('featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('premium', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rating', sa.Numeric(precision=4, scale=2), server_default='0', nullable=False),
    sa.Column('view_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('like_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('license_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('license_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_countries', sa.JSON(), nullable=False),
    sa.Column('blocked_countries', sa.JSON(), nullable=False),
    sa.Column('seo_title', sa.String(length=240), nullable=True),
    sa.Column('seo_description', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('license_end IS NULL OR license_start IS NULL OR license_end >= license_start', name=op.f('ck_content_license_date_range')),
    sa.CheckConstraint('rating >= 0 AND rating <= 10', name=op.f('ck_content_rating_range')),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_content_country_id_countries')),
    sa.ForeignKeyConstraint(['original_language_id'], ['languages.id'], name=op.f('fk_content_original_language_id_languages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content'))
    )
    op.create_index(op.f('ix_content_country_id'), 'content', ['country_id'], unique=False)
    op.create_index(op.f('ix_content_license_end'), 'content', ['license_end'], unique=False)
    op.create_index(op.f('ix_content_original_language_id'), 'content', ['original_language_id'], unique=False)
    op.create_index(op.f('ix_content_published_at'), 'content', ['published_at'], unique=False)
    op.create_index(op.f('ix_content_slug'), 'content', ['slug'], unique=True)
    op.create_index(op.f('ix_content_status'), 'content', ['status'], unique=False)
    op.create_index(op.f('ix_content_title'), 'content', ['title'], unique=False)
    op.create_index(op.f('ix_content_type'), 'content', ['type'], unique=False)
    op.create_index(op.f('ix_content_visibility'), 'content', ['visibility'], unique=False)
    op.create_table('crew_members',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('photo_url', sa.String(length=2048), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_crew_members_country_id_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crew_members'))
    )
    op.create_index(op.f('ix_crew_members_country_id'), 'crew_members', ['country_id'], unique=False)
    op.create_index(op.f('ix_crew_members_name'), 'crew_members', ['name'], unique=False)
    op.create_index(op.f('ix_crew_members_slug'), 'crew_members', ['slug'], unique=True)
    op.create_table('subtitles',
    sa.Column('video_asset_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('format', sa.Enum('vtt', 'srt', name='subtitle_format'), nullable=False),
    sa.Column('file_url', sa.String(length=2048), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_auto_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_subtitles_language_id_languages')),
    sa.ForeignKeyConstraint(['video_asset_id'], ['video_assets.id'], name=op.f('fk_subtitles_video_asset_id_video_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subtitles')),
    sa.UniqueConstraint('video_asset_id', 'language_id', 'label', name='track')
    )
    op.create_index(op.f('ix_subtitles_language_id'), 'subtitles', ['language_id'], unique=False)
    op.create_index(op.f('ix_subtitles_video_asset_id'), 'subtitles', ['video_asset_id'], unique=False)
    op.create_table('content_actors',
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('character_name', sa.String(length=180), nullable=False),
    sa.Column('role', sa.String(length=80), server_default='actor', nullable=False),
    sa.Column('is_lead', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_content_actors_actor_id_actors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_content_actors_content_id_content'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_actors')),
    sa.UniqueConstraint('content_id', 'actor_id', 'character_name', name='uq_content_actors_credit')
    )
    op.create_table('content_crew',
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('crew_member_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_content_crew_content_id_content'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crew_member_id'], ['crew_members.id'], name=op.f('fk_content_crew_crew_member_id_crew_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_crew')),
    sa.UniqueConstraint('content_id', 'crew_member_id', 'role', name='uq_content_crew_credit')
    )
    op.create_table('content_genres',
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_content_genres_content_id_content'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_content_genres_genre_id_genres'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'genre_id', name=op.f('pk_content_genres'))
    )
    op.create_table('content_tags',
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_content_tags_content_id_content'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_content_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'tag_id', name=op.f('pk_content_tags'))
    )
    op.create_table('movies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('video_asset_id', sa.Uuid(), nullable=True),
    sa.Column('access_type', sa.Enum('free', 'premium_subscription', 'coin_unlock', 'premium_or_coin', 'ad_unlock', 'scheduled_free', name='movie_access_type'), server_default='free', nullable=False),
    sa.Column('coin_price', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('coin_price >= 0', name=op.f('ck_movies_coin_price')),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name=op.f('ck_movies_duration')),
    sa.ForeignKeyConstraint(['id'], ['content.id'], name=op.f('fk_movies_id_content'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_asset_id'], ['video_assets.id'], name=op.f('fk_movies_video_asset_id_video_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movies'))
    )
    op.create_index(op.f('ix_movies_video_asset_id'), 'movies', ['video_asset_id'], unique=True)
    op.create_table('series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('total_seasons', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_episodes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('series_status', sa.Enum('draft', 'scheduled', 'ongoing', 'completed', 'paused', 'archived', name='series_status'), server_default='draft', nullable=False),
    sa.Column('orientation', sa.Enum('vertical', 'horizontal', 'mixed', name='content_orientation'), server_default='horizontal', nullable=False),
    sa.ForeignKeyConstraint(['id'], ['content.id'], name=op.f('fk_series_id_content'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series'))
    )
    op.create_index(op.f('ix_series_series_status'), 'series', ['series_status'], unique=False)
    op.create_table('seasons',
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=2048), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'published', 'archived', name='season_status'), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('season_number > 0', name=op.f('ck_seasons_number_positive')),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_seasons_series_id_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('series_id', 'season_number', name='number')
    )
    op.create_index(op.f('ix_seasons_series_id'), 'seasons', ['series_id'], unique=False)
    op.create_table('episodes',
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('video_asset_id', sa.Uuid(), nullable=True),
    sa.Column('orientation', sa.Enum('vertical', 'horizontal', 'mixed', name='episode_orientation'), server_default='horizontal', nullable=False),
    sa.Column('access_type', sa.Enum('free', 'premium_subscription', 'coin_unlock', 'premium_or_coin', 'ad_unlock', 'scheduled_free', name='episode_access_type'), server_default='free', nullable=False),
    sa.Column('coin_price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('premium', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('free_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('free_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'published', 'archived', name='episode_status'), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('coin_price >= 0', name=op.f('ck_episodes_coin_price')),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name=op.f('ck_episodes_duration')),
    sa.CheckConstraint('episode_number > 0', name=op.f('ck_episodes_number_positive')),
    sa.CheckConstraint('free_until IS NULL OR free_from IS NULL OR free_until >= free_from', name=op.f('ck_episodes_free_date_range')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_episodes_season_id_seasons')),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_episodes_series_id_series'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_asset_id'], ['video_assets.id'], name=op.f('fk_episodes_video_asset_id_video_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episodes')),
    sa.UniqueConstraint('series_id', 'episode_number', name='series_number')
    )
    op.create_index(op.f('ix_episodes_published_at'), 'episodes', ['published_at'], unique=False)
    op.create_index(op.f('ix_episodes_season_id'), 'episodes', ['season_id'], unique=False)
    op.create_index(op.f('ix_episodes_series_id'), 'episodes', ['series_id'], unique=False)
    op.create_index(op.f('ix_episodes_status'), 'episodes', ['status'], unique=False)
    op.create_index(op.f('ix_episodes_video_asset_id'), 'episodes', ['video_asset_id'], unique=True)
    seed_catalog_data()
    # ### end Alembic commands ###


def seed_catalog_data() -> None:
    now = datetime.now(UTC)
    countries = [
        ("BR", "Brazil", "BRL"),
        ("CA", "Canada", "CAD"),
        ("ES", "Spain", "EUR"),
        ("FR", "France", "EUR"),
        ("GB", "United Kingdom", "GBP"),
        ("HT", "Haiti", "HTG"),
        ("MX", "Mexico", "MXN"),
        ("US", "United States", "USD"),
    ]
    languages = [
        ("en", "English", "English"),
        ("fr", "French", "Français"),
        ("pt-BR", "Portuguese (Brazil)", "Português (Brasil)"),
        ("es", "Spanish", "Español"),
        ("ht", "Haitian Creole", "Kreyòl ayisyen"),
    ]
    genres = [
        "Romance",
        "Drama",
        "Revenge",
        "Billionaire",
        "Action",
        "Fantasy",
        "Mystery",
        "Comedy",
        "Historical",
        "Family",
        "Crime",
        "Thriller",
    ]
    tags = [
        "Secret Identity",
        "Arranged Marriage",
        "Royal",
        "Werewolf",
        "College",
        "CEO",
        "Family",
        "Crime",
    ]
    country_table = sa.table(
        "countries",
        sa.column("id", sa.Uuid()),
        sa.column("code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("currency", sa.String()),
        sa.column("active", sa.Boolean()),
        sa.column("sort_order", sa.Integer()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    language_table = sa.table(
        "languages",
        sa.column("id", sa.Uuid()),
        sa.column("code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("native_name", sa.String()),
        sa.column("active", sa.Boolean()),
        sa.column("sort_order", sa.Integer()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    genre_table = sa.table(
        "genres",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("slug", sa.String()),
        sa.column("active", sa.Boolean()),
        sa.column("sort_order", sa.Integer()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    tag_table = sa.table(
        "tags",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("slug", sa.String()),
        sa.column("active", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        country_table,
        [
            {
                "id": stable_id("country", code),
                "code": code,
                "name": name,
                "currency": currency,
                "active": True,
                "sort_order": index,
                "created_at": now,
                "updated_at": now,
            }
            for index, (code, name, currency) in enumerate(countries)
        ],
    )
    op.bulk_insert(
        language_table,
        [
            {
                "id": stable_id("language", code),
                "code": code,
                "name": name,
                "native_name": native_name,
                "active": True,
                "sort_order": index,
                "created_at": now,
                "updated_at": now,
            }
            for index, (code, name, native_name) in enumerate(languages)
        ],
    )
    op.bulk_insert(
        genre_table,
        [
            {
                "id": stable_id("genre", name.casefold()),
                "name": name,
                "slug": name.casefold().replace(" ", "-"),
                "active": True,
                "sort_order": index,
                "created_at": now,
                "updated_at": now,
            }
            for index, name in enumerate(genres)
        ],
    )
    op.bulk_insert(
        tag_table,
        [
            {
                "id": stable_id("tag", name.casefold()),
                "name": name,
                "slug": name.casefold().replace(" ", "-"),
                "active": True,
                "created_at": now,
                "updated_at": now,
            }
            for name in tags
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_video_asset_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_status'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_series_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_season_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_published_at'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_seasons_series_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_series_series_status'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_movies_video_asset_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_table('content_tags')
    op.drop_table('content_genres')
    op.drop_table('content_crew')
    op.drop_table('content_actors')
    op.drop_index(op.f('ix_subtitles_video_asset_id'), table_name='subtitles')
    op.drop_index(op.f('ix_subtitles_language_id'), table_name='subtitles')
    op.drop_table('subtitles')
    op.drop_index(op.f('ix_crew_members_slug'), table_name='crew_members')
    op.drop_index(op.f('ix_crew_members_name'), table_name='crew_members')
    op.drop_index(op.f('ix_crew_members_country_id'), table_name='crew_members')
    op.drop_table('crew_members')
    op.drop_index(op.f('ix_content_visibility'), table_name='content')
    op.drop_index(op.f('ix_content_type'), table_name='content')
    op.drop_index(op.f('ix_content_title'), table_name='content')
    op.drop_index(op.f('ix_content_status'), table_name='content')
    op.drop_index(op.f('ix_content_slug'), table_name='content')
    op.drop_index(op.f('ix_content_published_at'), table_name='content')
    op.drop_index(op.f('ix_content_original_language_id'), table_name='content')
    op.drop_index(op.f('ix_content_license_end'), table_name='content')
    op.drop_index(op.f('ix_content_country_id'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_actors_slug'), table_name='actors')
    op.drop_index(op.f('ix_actors_name'), table_name='actors')
    op.drop_index(op.f('ix_actors_country_id'), table_name='actors')
    op.drop_table('actors')
    op.drop_index(op.f('ix_video_assets_status'), table_name='video_assets')
    op.drop_index(op.f('ix_video_assets_provider'), table_name='video_assets')
    op.drop_index(op.f('ix_video_assets_playback_id'), table_name='video_assets')
    op.drop_table('video_assets')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_genres_slug'), table_name='genres')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    bind = op.get_bind()
    for enum_name in (
        "episode_status",
        "episode_access_type",
        "episode_orientation",
        "season_status",
        "series_status",
        "content_orientation",
        "movie_access_type",
        "subtitle_format",
        "age_rating",
        "content_visibility",
        "content_status",
        "content_type",
        "video_status",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
