'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';

import { Badge, PageHeading, QueryState } from '@/components/ui';
import { apiRequest, formatDate } from '@/lib/api';

type Comment = { id: string; body: string; status: string; is_pinned: boolean; is_spoiler: boolean; like_count: number; reply_count: number; target_type: string; target_id: string; author: { id: string; name: string; badge?: string | null }; created_at: string };
export default function CommentsPage() {
  const client = useQueryClient(); const [status, setStatus] = useState(''); const [q, setQ] = useState('');
  const params = new URLSearchParams({ page: '1', limit: '100' }); if (status) params.set('status', status); if (q) params.set('q', q);
  const query = useQuery({ queryKey: ['comments', status, q], queryFn: async () => (await apiRequest<Comment[]>(`/comments?${params}`)).data });
  const moderate = useMutation({ mutationFn: ({ id, action }: { id: string; action: string }) => apiRequest(`/comments/${id}`, { method: 'PATCH', body: JSON.stringify({ action, reason: `Moderated from Drovixa Admin: ${action}` }) }), onSuccess: () => client.invalidateQueries({ queryKey: ['comments'] }) });
  return <div className="page"><PageHeading eyebrow="Community safety" title="Comment moderation" description="Review, hide, restore, mark spam or pin community conversations." /><section className="panel"><div className="toolbar"><input className="field" placeholder="Search comments…" value={q} onChange={(e) => setQ(e.target.value)} /><select className="select" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option value="visible">Visible</option><option value="under_review">Under review</option><option value="hidden">Hidden</option><option value="spam">Spam</option><option value="deleted">Deleted</option></select></div>{moderate.error ? <div className="notice">{moderate.error.message}</div> : null}<QueryState loading={query.isLoading} error={query.error} empty={query.data?.length === 0}><div className="table-wrap"><table className="data-table"><thead><tr><th>Comment</th><th>Author</th><th>Target</th><th>Status</th><th>Activity</th><th>Actions</th></tr></thead><tbody>{query.data?.map((item) => <tr key={item.id}><td className="primary-cell" style={{ maxWidth: 380 }}><strong>{item.body}</strong><small>{formatDate(item.created_at)}{item.is_spoiler ? ' · Spoiler' : ''}</small></td><td>{item.author.name}{item.author.badge ? <><br/><Badge tone="accent">{item.author.badge}</Badge></> : null}</td><td>{item.target_type}<br/><small style={{ color: 'var(--muted)' }}>{item.target_id.slice(0,8)}</small></td><td><Badge tone={item.status === 'visible' ? 'success' : item.status === 'under_review' ? 'warning' : 'danger'}>{item.status}</Badge></td><td>{item.like_count} likes · {item.reply_count} replies</td><td><div className="actions">{item.status !== 'visible' ? <button className="button button-quiet" onClick={() => moderate.mutate({ id: item.id, action: 'restore' })}>Restore</button> : <button className="button button-danger" onClick={() => moderate.mutate({ id: item.id, action: 'hide' })}>Hide</button>}<button className="button button-quiet" onClick={() => moderate.mutate({ id: item.id, action: item.is_pinned ? 'unpin' : 'pin' })}>{item.is_pinned ? 'Unpin' : 'Pin'}</button><button className="button button-danger" onClick={() => moderate.mutate({ id: item.id, action: 'spam' })}>Spam</button></div></td></tr>)}</tbody></table></div></QueryState></section></div>;
}
